language: node_js
node_js:
- '4.1.2'
addons:
  sauce_connect: true
before_install:
- npm install -g -q bower
- npm install -g -q grunt-cli
install:
- npm install -q
before_script:
- ./node_modules/protractor/bin/webdriver-manager update
script:
- ./scripts/testserver.sh
- ./scripts/etcd.sh
- ./scripts/testonsauce.sh
env:
  global:
  - secure: ZxldMUNPjm7T/zGthCGvL2kbPLapcaJAj1VXYFw3he9TW4FG0H+E4u6/NEPSG5OdtG530NizguKJlbigmAN16eKaD+1MPkvBAY274RdFKBVv3Lemb1impM7VZC/zMOfDqmIPXYSzvp0Qgw1McS3W1x0Ub2arPS0CwW83LjackCQ=
  - secure: HJPtTG1LvHDn4YR2xieiOCa9qqaueo57c7YxghZSqEsp9Iecnb72l5nSa42ZsgBPnYiU7YYtI581B3qq66iUTU2KlB2ibFCg6yCfgHOvF3x8lEdbbQm+o2aQZbXeTGTZWYSxULEk4hLflFcI+9FvtcZKCFHB1cDvZ6euroVWe+g= 
sudo: false